name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        brew install mpich
        pip install -e ".[dev]"
        
    - name: Run tests
      run: |
        # Basic verification and core tests
        python scripts/verify_setup.py --ci-mode
        python scripts/test_network.py --local-only
        pytest tests/core -v
        
    - name: Check project structure
      run: |
        test -d src/models
        test -d src/distributed
        test -d tests