name: CI

on: [push, pull_request]

jobs:
  basic-verify:
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        
    - name: Install dependencies
      run: |
        brew install mpich
        python -m pip install --upgrade pip
        python -m pip install -e ".[dev]"
        
    - name: Basic verification
      run: |
        python scripts/verify_setup.py --ci-mode
        python scripts/test_network.py --local-only