name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        brew install mpich
        pip install -e ".[dev]"
        
    - name: Core tests
      run: |
        # Basic system verification
        python scripts/verify_setup.py --ci-mode
        
        # Core functionality test
        python scripts/test_network.py --local-only
        
        # Run essential unit tests
        pytest tests/core -v
        
    - name: Check basic structure
      run: |
        # Essential files
        test -f setup.py
        test -f requirements.txt
        test -f README.md
        test -f LICENSE
        
        # Core directories
        test -d src/models
        test -d src/distributed
        test -d tests
        test -d examples
        
    - name: Verify documentation
      run: |
        # Check README and examples
        python scripts/check_docs.py --basic-check
        
        # Verify example notebook exists
        test -f examples/distributed_training.ipynb