name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install system dependencies
      run: |
        brew install mpich
        
    - name: Install base Python dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install mpi4py  # Install mpi4py first
        
    - name: Install project dependencies
      run: |
        pip install -e ".[dev]"
        
    - name: Verify system setup
      run: |
        python scripts/verify_setup.py
        python scripts/test_network.py --local-only
        
    - name: Run tests
      run: |
        pytest tests/ -v
        
    - name: Run linting
      run: |
        black --check .
        isort --check-only .
        mypy src/