name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install system dependencies
      run: |
        brew install mpich
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mpi4py
        pip install -e ".[dev]"
        
    - name: Run tests
      run: |
        pytest tests/ -v
        
    - name: Run linting
      run: |
        black --check .
        isort --check-only .
        mypy src/