name: CI

on: [push, pull_request]

jobs:
  basic-verify:
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        brew install mpich
        pip install -e ".[dev]"
        
    - name: Basic verification
      run: |
        # Just verify basic setup and network
        python scripts/verify_setup.py --ci-mode
        python scripts/test_network.py --local-only